version: '3.9'
services:
  controller:
    image: ghcr.io/open-traffic-generator/ixia-c-controller:${CONTROLLER_VERSION:-latest}
    command: --accept-eula
    network_mode: "host"
    restart: always
  traffic_engine_1:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:${TRAFFIC_ENGINE_VERSION:-latest}
    restart: always
    privileged: true
    ports:
    - "${TCP_PORT_IFC1:-5555}:5555"
    cpuset: ${CPU_CORES_IFC1:-"0,1,2"}
    environment:
    - OPT_LISTEN_PORT=5555
    - ARG_IFACE_LIST=virtual@af_packet,eth0
    - OPT_NO_HUGEPAGES=Yes
  traffic_engine_2:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:${TRAFFIC_ENGINE_VERSION:-latest}
    restart: always
    privileged: true
    ports:
    - "${TCP_PORT_IFC2:-5556}:5555"
    cpuset: ${CPU_CORES_IFC2:-"0,3,4"}
    environment:
    - OPT_LISTEN_PORT=5555
    - ARG_IFACE_LIST=virtual@af_packet,eth0
    - OPT_NO_HUGEPAGES=Yes
  traffic_engine_3:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:${TRAFFIC_ENGINE_VERSION:-latest}
    restart: always
    privileged: true
    ports:
    - "${TCP_PORT_IFC3:-5557}:5555"
    cpuset: ${CPU_CORES_IFC3:-"0,5,6"}
    environment:
    - OPT_LISTEN_PORT=5555
    - ARG_IFACE_LIST=virtual@af_packet,eth0
    - OPT_NO_HUGEPAGES=Yes
  aur:
    image: ghcr.io/open-traffic-generator/ixia-c-app-usage-reporter:${AUR_VERSION:-latest}
    network_mode: "host"
    restart: always
