apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ixiatg-op-leader-election-role
  namespace: ixiatg-op-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ixiatg-op-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.keysight.com
  resources:
  - ixiatgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.keysight.com
  resources:
  - ixiatgs/finalizers
  verbs:
  - update
- apiGroups:
  - network.keysight.com
  resources:
  - ixiatgs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ixiatg-op-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ixiatg-op-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ixiatg-op-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ixiatg-op-manager-role
subjects:
- kind: ServiceAccount
  name: ixiatg-op-controller-manager
  namespace: ixiatg-op-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ixiatg-op-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ixiatg-op-proxy-role
subjects:
- kind: ServiceAccount
  name: ixiatg-op-controller-manager
  namespace: ixiatg-op-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ixiatg-op-leader-election-rolebinding
  namespace: ixiatg-op-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ixiatg-op-leader-election-role
subjects:
- kind: ServiceAccount
  name: ixiatg-op-controller-manager
  namespace: ixiatg-op-system
