apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ixia-c
  name: controller-config
  namespace: ixia-c
data:
  config.yaml: |
    location_map:
    - location: port1
      endpoint: otg-port1.ixia-c.svc.cluster.local:5555
