apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/namespace
  - ../../bases/otg-controller
  - port1
  - config-map.yaml

components:
  - ../../components/images
