apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ixia-c
    role: otg-port
  name: otg-port
  namespace: ixia-c
spec:
  containers:
    - env:
        - name: OPT_LISTEN_PORT
          value: "5555"
        - name: OPT_NO_PINNING
          value: "Yes"
        - name: ARG_IFACE_LIST
          value: virtual@af_packet,eth0
        - name: OPT_NO_HUGEPAGES
          value: "Yes"
        - name: WAIT_FOR_IFACE
          value: "Yes"
      image: ixia-c-traffic-engine:latest
      imagePullPolicy: IfNotPresent
      name: ixia-c-traffic-engine
      ports:
        - containerPort: 5555
          name: zeromq-port
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: zeromq-port
        periodSeconds: 5
      startupProbe:
        tcpSocket:
          port: zeromq-port
        periodSeconds: 5
        failureThreshold: 12
      securityContext:
        privileged: true
  restartPolicy: Always