apiVersion: v1
kind: Service
metadata:
  name: otg-port
  namespace: ixia-c
spec:
  ports:
    - name: zeromq
      port: 5555
      protocol: TCP
      targetPort: zeromq-port
  selector:
    role: otg-port