apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/otg-traffic-port

patches:
- target:
    version: v1
    kind: Pod
    name: otg-port
  path: pod-patch.yaml
- target:
    version: v1
    kind: Service
    name: otg-port
  path: service-patch.yaml