apiVersion: v1
kind: Pod
metadata:
  name: _
spec:
  initContainers:
    - name: init-setup
      image: ubuntu:22.04
      command:
        - bash
        - -c
        - apt-get update && apt-get install -y iptables && iptables -A INPUT -p udp --destination-port 7000:8000 -j DROP && iptables -A INPUT -p tcp --destination-port 7000:8000 -j DROP
      securityContext:
        privileged: true