apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/namespace
  - ../../bases/otg-controller
  - port1
  - port2
  - config-map.yaml

components:
  - ../../components/images

patches:
- path: init-container.yaml
  target:
    kind: Pod
    name: otg-port1
- path: init-container.yaml
  target:
    kind: Pod
    name: otg-port2