name: CI

env:
  PYTHON_VERSION: "3.8"
  GO_VERSION: "1.19"

on:
  push:

jobs:
  examples_curl:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Deploy Ixia-C
        run: |
          sed -n '58,61p' readme.md > deploy.sh
          sh deploy.sh
      - name: Setup and run tests
        run: |
          sed -n '90,97p' readme.md > test.sh
          sh test.sh
      - name: Get container logs
        if: always()
        run: |
          cd conformance && ./do.sh topo logs
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: examples_curl
          path: |
            conformance/logs

  examples_go_py:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Deploy Ixia-C
        run: |
          sed -n '58,61p' readme.md > deploy.sh
          sh deploy.sh
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup and run tests
        run: |
          sed -n '67,78p' readme.md > test.sh
          sh test.sh
      - name: Get container logs
        if: always()
        run: |
          cd conformance && ./do.sh topo logs
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: examples_go_py
          path: |
            conformance/logs

  deployments_k8s:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup Cluster
        run: |
          cd deployments/k8s
          sed -n '26,34p' readme.md > setup-cluster.sh
          sh setup-cluster.sh
      - name: Download images
        run: |
          cd deployments/k8s
          sed -n '42,49p' readme.md > download-images.sh
          sh download-images.sh
      - name: Setup Pods and Services
        run: |
          cd deployments/k8s
          sed -n '61,64p' readme.md > setup-pods-services.sh
          sh setup-pods-services.sh
      - name: Setup tests
        run: |
          cd deployments/k8s
          sed -n '75,77p' readme.md > setup-tests.sh
          sh setup-tests.sh
      - name: Run tests
        run: |
          cd deployments/k8s
          sed -n '85,86p' readme.md > run-tests.sh
          sh run-tests.sh

  deployments_k8s_network_emulation:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup Cluster
        run: |
          sed -n '49,60p' deployments/k8s/network-emulation/readme.md > setup-cluster.sh
          sh setup-cluster.sh
      - name: Download images
        run: |
          sed -n '66,91p' deployments/k8s/network-emulation/readme.md > download-images.sh
          sh download-images.sh
      - name: Setup Meshnet
        run: |
          sed -n '97,105p' deployments/k8s/network-emulation/readme.md > setup-meshnet.sh
          sh setup-meshnet.sh
      - name: Setup Interfaces
        run: |
          sed -n '113,118p' deployments/k8s/network-emulation/readme.md > setup-interfaces.sh
          sh setup-interfaces.sh
      - name: Setup Pods and Services
        run: |
          sed -n '124,131p' deployments/k8s/network-emulation/readme.md > setup-pods-services.sh
          sh setup-pods-services.sh
      - name: Setup and run tests
        run: |
          sed -n '141,143p' deployments/k8s/network-emulation/readme.md > test.sh
          sh test.sh
      - name: Cleanup
        run: |
          sed -n '153,157p' deployments/k8s/network-emulation/readme.md > cleanup.sh
          sh cleanup.sh