name: CICD

env:
  GO_VERSION: "1.18"

on:
  push:

jobs:
  kne_b2b:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup KNE cluster
        run: |
          ./do.sh new_k8s_cluster
      - name: Deploy KNE OTG back-to-back topology
        run: |
          ./do.sh topo new kneb2b
      - name: Teardown KNE OTG back-to-back topology
        run: |
          ./do.sh topo rm kneb2b
